docs/pull_request_template.md
=> Pull reuqest template

.circleci/config.yml, .gitignore, .vscode/settings.json, src/server/.eslintignore, src/server/.eslintrc.json, src/server/config.json, src/server/dbConnection.js, src/server/index.js, src/server/logger.js, src/server/models/user.js, src/server/package-lock.json, src/server/package.json, src/server/routes/register.js, src/server/routes/utilities/errorMessages.js, src/server/routes/utilities/statusCodes.js, src/server/utilities.js
Ok done. It's time for code review.
I'll set proper response instead of dummy, when we'll have some crypto things and public keys
#2
=> #2: Registration

.gitignore, src/server/package-lock.json, src/server/package.json
=> Updated package.json

README.md, src/server/package.json
N/A
README.md update and package.json from unusped dependencies
=> README changes & package.json cleanup

.vscode/settings.json
N/A
Added .eslintignore path in VSC settings to enable built-in linter to work better.
=> Added path to .eslintignore to vsc setting

src/server/package.json
#17
Introduced `npm start` into the project.
=> #17 npm start

.gitignore, .vscode/settings.json, README.md, src/server/.tests/generate-docs.spec.js, src/server/.tests/ws-routes/controllers/Room.spec.js, src/server/package-lock.json, src/server/package.json, src/server/protocol/protocol.json, src/server/ws-routes/controllers/Room.js, src/server/ws-routes/dataTypes.jsdoc, src/server/ws-routes/initializeWebSocketRouting.js, src/server/ws-routes/universalWebsocketEvents.jsdoc
#19 #39
- New command `npm run generate-docs` which creates docs in `/out` directory
- Docs for `/Room` web socket namespace
- Room API redesign
- Ignoring `/out` directory in server directory which will now be used to store generated docs
=> #19 #39 Documentation of /Room namespace

.circleci/config.yml, .gitignore, src/server/.tests/utilities.spec.js, src/server/package-lock.json, src/server/package.json, src/server/utilities.js
#31 
- Added test coverage checks by `npm run test-coverage` command
- Added test coverage to be run in CI config.
=> #31 CI pipeline tests coverage check

src/client/src/.tests/components/chatpage.test.js, src/client/src/components/chatpage.js, src/client/src/index.js
resolves #62 
Removed hacky comments and added tests for callbacks. Review requested for test quality.
=> Added tests for callbacks

src/client/src/App.js, src/client/src/index.js
Resolves #69 
Error was based on App.js containing an import statement for the css, moved import to index.js, another error popped up when I changed registerServiceWorker to a const, so I will leave it as an import for now.
Adding WIP label to include tests for application startup
=> Startup fix

src/client/package-lock.json, src/client/package.json, src/client/src/.tests/components/chatpage.test.js, src/client/src/App.js, src/client/src/components/chatpage.js
Reolves #72 , #73 
- Correct homepath to solve component overlapping bug.
- Added missing return statement to generateRooms to show room list
- Bound this to socket callbacks
**Requirements**
Please use white box testing methods during review to ensure stability of branch
=> #73 chatpage fix

src/server/.tests/tools/.eslintrc.json, src/server/.tests/tools/webSocketsTester.css, src/server/.tests/tools/webSocketsTester.html, src/server/.tests/tools/webSocketsTester.js
resolves #48 
- Websockets testing tool now automatically set up event listeners, namespaces and possible event
- expand `protocol.json` to include events parameters
=> #48 Automated ws testing tool configuration accoridng to protocol.json

src/client/.eslintrc.json, src/client/src/.eslintrc.json, src/client/src/.tests/components/chatpage.test.js, src/client/src/components/chatpage.js, src/client/src/components/register.js
resolves #75 
Fixed eslint configuration cascading in client
=> #75 Eslint frontend hotfix

src/server/.tests/ws-routes/controllers/Room.spec.js, src/server/ws-routes/controllers/Room.js
resolves #82 
- Changed ws event emitting to only prompt sender
- Adjusted tests
=> #82 Broadcasting listUsers to everyone in the room

.circleci/config.yml, .gitignore, Procfile, package.json, src/server/.tests/configFileService.spec.js, src/server/configFileService.js, src/server/dbConnection.js, src/server/init.js, src/server/package-lock.json, src/server/package.json
resolves #45 
- Server uses now environmental variables for port with higher priority than config
- Server can use now environmental variable for HTTP port
- Server is compatible with heroku
- GitHub repo is synced with heroku
=> #45 Configure app to work with heroku

.circleci/config.yml
resolves #88 
- Changed MongoDB CircleCI docker image
=> CircleCI failing on all branches

src/server/frontEnd/package.json, src/server/frontEnd/public/index.html, src/server/frontEnd/src/.tests/components/chatpage.test.js, src/server/frontEnd/src/App.css, src/server/frontEnd/src/App.js, src/server/frontEnd/src/avatar.svg, src/server/frontEnd/src/components/chatpage.js, src/server/frontEnd/src/components/room.js, src/server/frontEnd/src/utils/io-protocol.json, src/server/frontEnd/src/utils/sockets/ws-routing.js, src/server/init.js, src/server/ws-routes/controllers/Room.js, src/server/ws-routes/controllers/Users.js
- resolves #80 
-  Joining room by its name
-  Dialing room from connected rooms list
- Searching users by username
=> #80 Rooms joining/creation + searching for users frontend implementation

package.json, src/server/frontEnd/package-lock.json, src/server/frontEnd/package.json, src/server/frontEnd/src/initializeRedux.js, src/server/package-lock.json, src/server/package.json, src/server/prod.webpack.config.js
- resolves #109 
- Heroku build process fix
=> Heroku fix after frontend refactor

README.md
resolves #129 
README changes for @Rejzor
=> #129 Main README update

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
**Related tickets**
resolves #128 
**Description**
A templates which will be placed when putting a new ticket.
=> #128 Create Issue templates

README.md, package.json, src/server/frontEnd/package-lock.json, src/server/package-lock.json
=> #135 Single command to build project

codecov.yml
resolves #170 
Lift restrictions implied by  codecov.
=> #170 Remove codecov blocking ability

README.md, src/server/frontEnd/package-lock.json, src/server/package-lock.json
=> #136-cypress-doesn't-work-locally

gulpfile.js
resolves #182 
Edited gulpfile.js
=> #182 Changed gulpfile.js to use npm ci instead of npm install.

src/server/.tests/mocha/ws-routes/controllers/Room.spec.js, src/server/.tests/mocha/ws-routes/controllers/Users.spec.js, src/server/frontEnd/src/.tests/theme/scenes/chatpage.spec.js, src/server/frontEnd/src/services/roomsManagement/room.actions.js, src/server/frontEnd/src/services/sagas/webSocketListener.saga.js, src/server/frontEnd/src/theme/scenes/chatpage/components/chatWindow/chatHistory/chatHistory.js, src/server/ws-routes/controllers/Room.js, src/server/ws-routes/controllers/Users.js, src/server/ws-routes/responses/FindResponse.class.js, src/server/ws-routes/responses/JoinResponse.class.js, src/server/ws-routes/responses/LeaveResponse.class.js, src/server/ws-routes/responses/ListMembersResponse.class.js, src/server/ws-routes/responses/MessageResponse.class.js, src/server/ws-routes/responses/Response.class.js
=> #168 standardise backend ws responses

src/server/frontEnd/src/.tests/theme/components/Avatar.spec.js, src/server/frontEnd/src/.tests/theme/components/__snapshots__/Avatar.spec.js.snap, src/server/frontEnd/src/theme/components/avatar/avatar.js, src/server/frontEnd/src/theme/components/avatar/avatarSizes.js, src/server/frontEnd/src/theme/scenes/chatpage/chatpage.js, src/server/frontEnd/src/theme/scenes/chatpage/components/chatWindow/chatHistory/chatMessage/chatMessage.js, src/server/frontEnd/src/theme/scenes/chatpage/components/usersList/usersListElement/usersListElement.js
=> 179 avatar component

gulpfile.js, src/server/frontEnd/src/.tests/theme/components/Icon.spec.js, src/server/frontEnd/src/.tests/theme/components/__snapshots__/Icon.spec.js.snap, src/server/frontEnd/src/theme/components/icon/icon.js, src/server/frontEnd/src/theme/components/icon/iconSizes.js
=> 178 icon component

src/server/.tests/mocha/routes/controllers/logOutUser.spec.js, src/server/.tests/mocha/ws-routes/controllers/Room.spec.js, src/server/models/message.js, src/server/package-lock.json, src/server/package.json, src/server/ws-routes/controllers/Room.js, src/server/ws-routes/responses/MessageResponse.class.js, src/server/ws-routes/webSocketRouting.js
=> #142 Storing messages history

src/server/.tests/mocha/routes/controllers/logOutUser.spec.js, src/server/.tests/mocha/ws-routes/controllers/Room.spec.js, src/server/frontEnd/src/services/roomsManagement/room.actions.js, src/server/frontEnd/src/services/roomsManagement/roomsManagement.actions.js, src/server/frontEnd/src/services/roomsManagement/roomsManagement.reducer.js, src/server/frontEnd/src/services/sagas/webSocketEmitters.saga.js, src/server/frontEnd/src/services/sagas/webSocketListener.saga.js, src/server/frontEnd/src/theme/scenes/chatpage/chatpage.js, src/server/frontEnd/src/theme/scenes/chatpage/components/roomsDialer/roomsDialer.js, src/server/frontEnd/src/theme/scenes/chatpage/components/roomsDialer/roomsListElement/roomsListElement.js, src/server/utilities.js, src/server/ws-routes/controllers/Room.js
=> #215 Leave room feature
